### ISSUE TITLE
Is there a way to open plugin's guis through the python scripting?

### ISSUE THREAD

**Issue by DepreTux** [wiffbi/Selected_Track_Control#1]
Hi!

Thanks for your script! I'm using it on one of my controllers and works wonders.
I'm also going through it in order to customize the one for my novation remote sl controller.
My question to you is if you know the live's api method to open a vst gui.

That would allow me to avoid mouse and keyboard completely, and would be great to know.

Once again, thanks for your work and help.

**Comment by wiffbi** [comment]
AFAIK there is no way to open a vst (or AudioUnit) GUI via the API or even any other way than using the mouse (cmd-alt-p AFAIK only toggles visibility of all currently open vst-GUIs).

You could try with a MIDI to keystroke-utility like midistroke (OS X) to send cmd-alt-p to open PlugIn-windows – but that AFAIK only opens the last opened PlugIn-windows that were closed with the same shortcut cmd-alt-p (so basically it is a visibility toggle for open plugin-windows).

**Comment by DepreTux** [comment]
Hey, thanks for your help! I guess I'll still have to do this with the mouse.

Have a good one!
