### ISSUE TITLE
REQ: Control non-selected tracks

### ISSUE THREAD

**Issue by mblais** [wiffbi/Selected_Track_Control#3]
For my use of this project I need to be able to control (Arm, Solo, Mute) directly for any track by number, without first making it the current track. Is there a chance you could add this capability?  Thanks.

**Comment by mblais** [comment]
NVM - I'm going to attempt it myself :)

**Comment by wiffbi** [comment]
Sorry for my delayed reply. You could use STC for this, if you can make your controller send multiple MIDI commands. It would basically work in two steps: first, send MIDI command CC #11 with the nr of the track as value (up to 128 tracks possible) – this will make it the currently selected track. Then send the MIDI command to arm, mute, whatever.

As this might be rather cumbersome, I’d suggest you have a look at the _Framework-classes. You could use a SessionComponent to make a huge redbox and assign the controls you need. I used it in another project for my PocketDial: https://github.com/wiffbi/Pocket_Dial you can have a look there to get you started using the SessionComponent.

How many tracks do you want to control? If it is only up to 16 tracks then one could also use the MIDI channel to decide which track to control.

**Comment by mblais** [comment]
Thanks for the reply Richard. I was able to extend STC to accommodate a few new commands (Arm, Solo, Mute directed to a specific track, without changing the currently-selected track).

I'm still hacking on it, but eventually it might be a useful addition, if you're interested.
